version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: ["redis-server", "--requirepass $${REDIS_PASSWORD}"]
    env_file:
      - .env

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A scheduler.celery_app worker --pool=solo --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  celery_beat:
    build: .
    command: celery -A scheduler.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:



