name: CI
on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Python tests
        env:
          HF_API_KEY: dummy
        run: |
          PYTHONPATH=. pytest -q
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Java modules
        run: |
          cd track1Backend && ./gradlew build -x test --no-daemon
      - name: Frontend lint
        run: |
          cd track2 && npm ci && npm run lint --if-present
