

name: Build and Deploy Docker Image
on:
  push:
    branches: [ "master" ]
    paths:
      - 'track1Backend/application/Dockerfile'
      - 'deploy.sh'
      - '.github/workflows/backend-deployment.yml'
      - '**.yml'
      - 'track1Backend'
      - 'compose.yaml'
  pull_request:
    branches:
      - 'master'
    types:
      - closed


jobs:

  docker-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ { project: 'track1Backend/application' , image: 'track1-backend' }]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: test l
        working-directory: ${{ matrix.project.project }}
        run: ls
      - name : allow access to gradlew
        working-directory: ${{ matrix.project.project }}
        if: ${{ matrix.project.project == 'track1Backend/application' }}
        run: chmod +x gradlew
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          working-directory: ${{ matrix.project.project }}
          context: ${{ matrix.project.project }}
          file: ${{ matrix.project.project }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.project.image }}:latest
  
  
  
  
  
  

#  deploy:
#
#    runs-on: ubuntu-latest
#    needs:
#      - docker-build
#    steps:
#      - uses: actions/checkout@v1
#      - name: List files
#        run: ls -al
#      #        - name: Check SSH key
#      #          run: echo "${{ secrets.SSH_KEY }}" | ssh-keygen -lf -
#      #
#      - name: Copy repository contents via scp
#        uses: appleboy/scp-action@master
#        with:
#          HOST: ${{ secrets.SSH_HOST }}
#          USERNAME: ${{ secrets.SSH_USER }}
#          PASSWORD: ${{ secrets.SSH_PASSWORD }}
#          source: "compose.yaml"
#          target: "menucha/"
#      - uses: appleboy/ssh-action@v1.0.3
#        name: Deploy the application
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          script: |
#            cd /menucha
#            docker-compose down
#            docker-compose pull
#            docker-compose up -d
#
#
